In [2]:
import pandas as pd
import random
import os
import numpy as np

from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split



import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import  metrics
from sklearn.metrics import accuracy_score



from sklearn.cluster import KMeans

In [3]:
class CFG:
    SEED = 42

In [4]:
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
seed_everything(CFG.SEED) # Seed 고정

In [5]:
train = pd.read_csv('./train.csv')
test = pd.read_csv('./test.csv')



def get_x_y(df):
    if 'class' in df.columns:
        df_x = df.drop(columns=['id', 'class'])
        df_y = df['class']
        return df_x, df_y
    else:
        df_x = df.drop(columns=['id'])
        return df_x
    
train_x, train_y = get_x_y(train)
test_x = get_x_y(test)
train_x

,father,mother,gender,trait,SNP_01,SNP_02,SNP_03,SNP_04,SNP_05,SNP_06,SNP_07,SNP_08,SNP_09,SNP_10,SNP_11,SNP_12,SNP_13,SNP_14,SNP_15
0,0,0,0,2,G G,A G,A A,G A,C A,A A,A A,G G,A A,G G,A G,A A,A A,A A,A A
1,0,0,0,2,A G,A G,C A,A A,A A,A G,A A,G A,A A,A G,A A,G A,G G,A A,A A
2,0,0,0,2,G G,G G,A A,G A,C C,G G,A A,G A,G A,A G,A A,A A,A A,A A,A A
3,0,0,0,1,A A,G G,A A,G A,A A,G G,G G,A A,G G,A G,G G,G G,G G,A A,G G
4,0,0,0,2,G G,G G,C C,A A,C C,A A,A A,A A,A A,G G,A A,A A,A G,A A,G A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,0,0,0,2,A G,A G,A A,G A,C C,A G,A A,G A,A A,G G,A G,G A,A A,A A,A A
258,0,0,0,2,G G,A A,C A,A A,A A,A G,G A,G A,A A,A G,A G,A A,A G,A A,G A
259,0,0,0,1,A G,G G,A A,G A,A A,A G,G G,G A,G A,A A,G G,G G,G G,C A,G G
260,0,0,0,1,A A,G G,A A,G A,A A,G G,G G,A A,G A,A G,A G,G A,G G,C A,G G
261,0,0,0,2,G G,A G,C A,G G,C C,A G,A A,A A,A A,G G,A A,A A,G G,A A,G A

In [6]:
class_le = preprocessing.LabelEncoder()
snp_le = preprocessing.LabelEncoder()
snp_col = [f'SNP_{str(x).zfill(2)}' for x in range(1,16)]

snp_data = []
for col in snp_col:
    snp_data += list(train_x[col].values)

train_y = class_le.fit_transform(train_y)
snp_le.fit(snp_data)

LabelEncoder()

In [7]:
for col in train_x.columns:
    if col in snp_col:
        train_x[col] = snp_le.transform(train_x[col])
        test_x[col] = snp_le.transform(test_x[col])

In [8]:
data_points = train_x.values
kmeans = KMeans(n_clusters = 3).fit(data_points)

In [9]:
kmeans.cluster_centers_

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.00000000e+00,  3.46666667e+00,  8.53333333e-01,
         1.57333333e+00,  5.06666667e-01,  1.62666667e+00,
         1.14666667e+00,  7.46666667e-01,  3.20000000e+00,
         5.33333333e-02,  2.56000000e+00,  5.46666667e-01,
         8.00000000e-01,  2.74666667e+00,  3.86666667e-01,
         3.20000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  5.21739130e-01,  4.65217391e+00,
        -6.66133815e-16,  4.40579710e+00,  4.05797101e-01,
         3.84057971e+00,  4.73913043e+00,  6.37681159e-01,
         3.57971014e+00,  7.10144928e-01,  4.24637681e+00,
         4.63768116e+00,  4.82608696e+00,  1.98550725e+00,
         4.40579710e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.00000000e+00,  4.06779661e+00,  2.13559322e+00,
         1.77966102e+00,  2.33050847e+00,  2.27118644e+00,
         1.40677966e+00,  5.42372881e-01,  4.19491525e+00,
         7.88135593e-01,  4.93220339e+00,  1.50000000e+00,
         1.50000000e+00,  1.11016949e+00,  9.32203390e-02,
         1.11016949e+00]])

In [10]:
train_x['cluster_id'] = kmeans.labels_
train_x

,father,mother,gender,trait,SNP_01,SNP_02,SNP_03,SNP_04,SNP_05,SNP_06,SNP_07,SNP_08,SNP_09,SNP_10,SNP_11,SNP_12,SNP_13,SNP_14,SNP_15,cluster_id
0,0,0,0,2,5,1,0,4,2,0,0,5,0,5,1,0,0,0,0,2
1,0,0,0,2,1,1,2,0,0,1,0,4,0,1,0,4,5,0,0,0
2,0,0,0,2,5,5,0,4,3,5,0,4,4,1,0,0,0,0,0,2
3,0,0,0,1,0,5,0,4,0,5,5,0,5,1,5,5,5,0,5,1
4,0,0,0,2,5,5,3,0,3,0,0,0,0,5,0,0,1,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,0,0,0,2,1,1,0,4,3,1,0,4,0,5,1,4,0,0,0,2
258,0,0,0,2,5,0,2,0,0,1,4,4,0,1,1,0,1,0,4,0
259,0,0,0,1,1,5,0,4,0,1,5,4,4,0,5,5,5,2,5,1
260,0,0,0,1,0,5,0,4,0,5,5,0,4,1,1,4,5,2,5,1
261,0,0,0,2,5,1,2,5,3,1,0,0,0,5,0,0,5,0,4,0

In [11]:
X_train, X_test, y_train, y_test = train_test_split(train_x, train_y, test_size=0.2)

In [12]:
train_y

array([1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 0, 0, 0, 0, 2, 1, 1,
       0, 1, 2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 0, 1, 1, 1, 1, 1, 0,
       2, 1, 1, 0, 2, 0, 0, 2, 0, 2, 1, 1, 0, 0, 2, 2, 1, 0, 2, 2, 0, 2,
       2, 0, 1, 2, 2, 2, 0, 1, 1, 1, 2, 1, 2, 0, 1, 1, 2, 0, 2, 0, 2, 2,
       2, 1, 1, 1, 2, 2, 1, 1, 2, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2, 2, 0,
       1, 2, 0, 1, 2, 0, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 0, 1, 0, 2, 2, 2,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0, 0, 2, 2, 0, 0, 2, 2, 2,
       2, 0, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 0, 1, 1, 2,
       1, 2, 0, 1, 0, 1, 0, 2, 2, 1, 2, 1, 2, 1, 0, 0, 1, 2, 0, 0, 2, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 2, 1, 2, 1, 2, 1, 0, 2, 0, 0, 2,
       2, 1, 1, 1, 0, 1, 0, 1, 0, 2, 1, 0, 1, 1, 1, 1, 2, 0, 0, 1])

In [13]:
clf = RandomForestClassifier(random_state=CFG.SEED)
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [14]:
preds = clf.predict(X_test)
print('Done.')
print(preds)

Done.
[1 1 1 2 1 2 2 0 1 1 2 0 2 2 1 2 1 1 0 2 1 1 2 1 2 1 2 1 1 0 1 1 0 1 1 1 2
 1 2 0 0 1 1 1 0 1 2 1 1 2 2 1 1]

In [15]:
accuracy_score(y_test, preds)

0.9811320754716981

In [54]:
submit = pd.read_csv('./sample_submission.csv')

submit['class'] = class_le.inverse_transform(preds)

submit.to_csv('./answer/submit.csv', index=False)